---

- hosts: all
  become: true
  pre_tasks:

  - name: Ubuntu Servers fixing by Dpkg
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Remote Ubuntu server Update and Upgrade
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: Ubuntu
  become: true
  roles:
    - role: Ubuntu
